import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('character/mapa-nb8.glb')
  return (
    <group {...props} dispose={null} scale={[10, 10, 10]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_1.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_2.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_3.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_4.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_5.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_6.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_7.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_8.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_9.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_10.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_11.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_12.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_13.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_14.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_15.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_16.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_17.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_18.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_19.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_20.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_21.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_22.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_23.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_24.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_25.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_26.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_27.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_28.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_29.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_30.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_31.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_32.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_33.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_34.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_35.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_36.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_37.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_38.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_39.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_40.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_41.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_42.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_43.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_44.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_45.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_46.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_47.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_48.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_49.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_50.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_51.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_52.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_53.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_54.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_55.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_56.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_57.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_58.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_59.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_60.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_61.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_62.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_63.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_64.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_65.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_66.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_67.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_68.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_69.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_70.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_71.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_72.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_73.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_74.geometry}
        material={materials.buildings}
      />
      <mesh castShadow receiveShadow geometry={nodes.map_1.geometry} material={materials.floor} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_2.geometry}
        material={materials.tree_area}
      />
      <mesh castShadow receiveShadow geometry={nodes.map_3.geometry} material={materials.walkway} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_4.geometry}
        material={nodes.map_4.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_5.geometry}
        material={materials.buildings}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_6.geometry}
        material={materials['important_buildings.001']}
      />
    </group>
  )
}

useGLTF.preload('character/mapa-nb8.glb')